# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Scribbles
tagline:             'There may be a better title'
description:         ''
url:                 
baseurl:             ''
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
exclude: archive_examples
markdown: kramdown

# About/contact
author:
  name:              'Nick Wong'
  url:               hi
  email:             nicholaswong65656ster@gmail.com

# Custom vars
version:             1.0.0
